version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "00:00"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "automated"
    assignees:
      - "krpeacocke"
    reviewers:
      - "krpeacocke"