services:
  whmrqst_prod:
    image: whmrqst
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    ports:
      - "${PROD_PORT}:5000"
    environment:
      - FLASK_ENV=production
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_HOST=mongo_prod
      - MONGO_PORT=${MONGO_PORT}
      - MONGO_DB_NAME=${MONGO_DB_NAME}
      - SECRET_KEY=${SECRET_KEY}
    networks:
      - internal_network_prod
      - default

  mongo_prod:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongo_data_prod:/data/db
    networks:
      - internal_network_prod

volumes:
  mongo_data_prod:

networks:
  internal_network_prod:
    internal: true