services:
  whmrqst:
    image: whmrqst
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    ports:
      - 5000:5000
    environment:
      - FLASK_APP=/app/src/run.py  # Updated path to reflect Docker structure
      - FLASK_ENV=development

  mongo:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: