services:
  whmrqst_debug:
    image: whmrqst
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    command: ["sh", "-c", "pip install debugpy -t /tmp && python -Xfrozen_modules=off /tmp/debugpy --wait-for-client --listen 0.0.0.0:5679 -m flask run --no-debugger --no-reload --host 0.0.0.0 --port 5000"]
    ports:
      - "${DEBUG_PORT}:5000"
      - "5679:5679"
    environment:
      - FLASK_APP=${FLASK_APP:-src/app:create_app}
      - FLASK_ENV=development
      - PYDEVD_DISABLE_FILE_VALIDATION=1
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_HOST=mongo_debug
      - MONGO_PORT=${MONGO_PORT}
      - MONGO_DB_NAME=${MONGO_DB_NAME}
      - SECRET_KEY=${SECRET_KEY}
    volumes:
      - ../:/app
    networks:
      - internal_network_debug

  mongo_debug:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongo_data_debug:/data/db
    networks:
      - internal_network_debug

volumes:
  mongo_data_debug:

networks:
  internal_network_debug:
    internal: true