services:
  whmrqst:
    image: whmrqst
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    command: ["sh", "-c", "pip install debugpy -t /tmp && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 -m flask run --no-debugger --no-reload --host 0.0.0.0 --port 5000"]
    ports:
      - 5000:5000
      - 5678:5678
    environment:
      - FLASK_APP=/app/src/run.py     # Path to the app file inside the Docker container
      - FLASK_ENV=development          # Development environment
    volumes:
      - ../:/app                         # Bind mount to allow live code updates

  mongo:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
