name: Apply Branch Protection Rules

on:
  push:
    branches:
      - main

jobs:
  apply-branch-protection:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Apply Branch Protection Rules for main
        run: |
          curl -X PUT -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/branches/main/protection \
            -d '{
              "required_status_checks": {
                "strict": true,
                "contexts": ["enforce-gitflow"]
              },
              "enforce_admins": true,
              "required_pull_request_reviews": {
                "dismiss_stale_reviews": true,
                "require_code_owner_reviews": true,
                "required_approving_review_count": 0
              },
              "restrictions": null,
              "required_linear_history": true,
              "allow_force_pushes": false,
              "allow_deletions": false
            }'

      - name: Apply Branch Protection Rules for develop
        run: |
          curl -X PUT -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/branches/develop/protection \
            -d '{
              "required_status_checks": {
                "strict": true,
                "contexts": ["enforce-gitflow"]
              },
              "enforce_admins": true,
              "required_pull_request_reviews": {
                "dismiss_stale_reviews": true,
                "require_code_owner_reviews": true,
                "required_approving_review_count": 1
              },
              "restrictions": null,
              "required_linear_history": true,
              "allow_force_pushes": false,
              "allow_deletions": false
            }'