name: Generate Tests from Wiki

on:
  workflow_dispatch: # This allows you to manually trigger the workflow
  push:
    paths:
      - 'wiki/**/*.md'

jobs:
  generate-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python Environment
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest # Install testing framework

      - name: Generate Test Templates
        id: generate_tests
        run: |
          mkdir -p tests/generated
          python scripts/generate_tests.py

      - name: Display Generated Tests
        run: |
          cat tests/generated/*