name: Generate Tests from Wiki

on:
  workflow_dispatch:
  push:
    paths:
      - 'wiki/**/*.md'

jobs:
  generate-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python Environment
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: List Directory Contents
        run: ls -R

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest

      - name: Generate Test Templates
        id: generate_tests
        run: |
          mkdir -p tests/generated
          python scripts/generate_tests.py # Adjust this path based on your file location

      - name: Display Generated Tests
        run: |
          cat tests/generated/*