name: Generate Tests with Copilot CLI

on:
  workflow_dispatch:  # Allows manual triggering of this workflow

jobs:
  generate-and-run-copilot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python Environment
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install GitHub Copilot CLI
        run: |
          npm install -g @githubnext/github-copilot-cli

      - name: Authenticate Copilot CLI
        run: |
          echo "$GITHUB_TOKEN" | github-copilot-cli auth login --with-token

      - name: Generate Test Templates
        run: |
          mkdir -p tests
          python scripts/generate_tests.py

      - name: Generate Tests with Copilot
        run: |
          cd tests
          for file in *.py; do
            echo "Generating code for $file"
            github-copilot-cli generate --file $file --prompt "Implement test cases for the following requirement based on the template provided." --overwrite
          done

      - name: Commit Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add tests
          git commit -m "Generated tests with Copilot CLI"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: "Generated tests with Copilot CLI"
          branch: copilot-generated-tests
          title: "Generated Tests with Copilot CLI"
          body: |
            This PR contains auto-generated test cases using GitHub Copilot CLI.
            Please review the test cases and make any necessary adjustments.