# Generated by Django 5.2.6 on 2026-04-05 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaign", "0004_expedition_and_definition"),
    ]

    operations = [
        migrations.AddField(
            model_name="hero",
            name="alive",
            field=models.BooleanField(default=True),
        ),
    ]
