# Generated by Django 6.1.1 on 2026-09-30 23:49

from django.db import migrations, models


def seed_core_rules(apps, schema_editor):
    game_rule_model = apps.get_model("campaign", "GameRuleDef")
    shop_model = apps.get_model("campaign", "ShopDef")
    game_rule_model.objects.using(schema_editor.connection.alias).get_or_create(
        code="core",
        defaults={
            "name": "Core Campaign Rules",
            "definition": {
                "source": "whq_roleplay_book",
                "expedition": {
                    "minimum_injury_target": 2,
                    "risk_profiles": {
                        "cautious": {
                            "reward_pct": 0.75,
                            "challenge_mod": -1,
                            "injury_mod": -1,
                            "morale_on_success": 0,
                            "morale_on_failure": -1,
                            "supply_cost_modifier": -1,
                        },
                        "standard": {
                            "reward_pct": 1.0,
                            "challenge_mod": 0,
                            "injury_mod": 0,
                            "morale_on_success": 1,
                            "morale_on_failure": -1,
                            "supply_cost_modifier": 0,
                        },
                        "reckless": {
                            "reward_pct": 1.4,
                            "challenge_mod": 2,
                            "injury_mod": 1,
                            "morale_on_success": 2,
                            "morale_on_failure": -1,
                            "supply_cost_modifier": 1,
                        },
                    },
                },
                "travel": {
                    "hazards_by_settlement": {
                        "village": 2,
                        "town": 4,
                        "city": 6,
                    },
                    "maximum_hazards_per_trip": 100,
                },
                "economy": {
                    "stock_dice_by_settlement": {
                        "village": 1,
                        "town": 2,
                        "city": 3,
                    }
                },
                "settlement": {
                    "catastrophic_start_day": 14,
                    "catastrophic_interval_days": 7,
                    "rule_flags": {
                        "future_income": [
                            {
                                "target": "hero",
                                "field": "investment_active",
                                "value": True,
                            }
                        ],
                        "forced_departure_or_delay": [
                            {
                                "target": "party",
                                "field": "forced_departure",
                                "value": True,
                            }
                        ],
                        "may_force_departure": [
                            {
                                "target": "party",
                                "field": "forced_departure",
                                "value": True,
                            }
                        ],
                        "service_delay": [
                            {
                                "target": "hero",
                                "field": "days_unavailable",
                                "operation": "add",
                                "value": 7,
                            }
                        ],
                        "bed_rest": [
                            {
                                "target": "hero",
                                "field": "days_unavailable",
                                "operation": "add",
                                "value": 2,
                            }
                        ],
                        "pet_dog": [
                            {"target": "hero", "field": "has_pet_dog", "value": True}
                        ],
                        "jail": [
                            {
                                "target": "hero",
                                "field": "days_unavailable",
                                "operation": "add",
                                "value": 1,
                            }
                        ],
                        "reroll_attack_once": [
                            {
                                "target": "hero",
                                "field": "temple_reroll_charges",
                                "operation": "add",
                                "value": 1,
                            }
                        ],
                        "possible_disguise_or_exile": [
                            {"target": "hero", "field": "in_disguise", "value": True}
                        ],
                        "recovery_delay": [
                            {
                                "target": "hero",
                                "field": "days_unavailable",
                                "operation": "add",
                                "value": 1,
                            }
                        ],
                    },
                    "catastrophic_state_by_table_roll": {
                        "3": [
                            {
                                "target": "party",
                                "field": "forced_departure",
                                "value": True,
                            }
                        ],
                        "5": [
                            {
                                "target": "party",
                                "field": "hardship_price_multiplier",
                                "value": 4,
                            }
                        ],
                        "10": [
                            {
                                "target": "party",
                                "field": "disease_risk_active",
                                "value": True,
                            }
                        ],
                        "11": [
                            {
                                "target": "party",
                                "field": "forced_departure",
                                "value": True,
                            }
                        ],
                        "12": [
                            {
                                "target": "party",
                                "field": "disease_risk_active",
                                "value": True,
                            }
                        ],
                    },
                },
                "location": {
                    "archetype_gates": {
                        "wizards_guild": "mage",
                        "elf_quarter": "ranger",
                        "dwarf_guildmasters": "warrior",
                    },
                    "skill_granting_locations": [
                        "wizards_guild",
                        "elf_quarter",
                        "dwarf_guildmasters",
                    ],
                },
            },
        },
    )
    for settlement_size, availability_dice in (
        ("village", 1),
        ("town", 2),
        ("city", 3),
    ):
        shop_model.objects.using(schema_editor.connection.alias).get_or_create(
            name=f"{settlement_size.title()} Market",
            defaults={
                "settlement_size": settlement_size,
                "stock_table": {
                    "source": "whq_roleplay_book",
                    "availability_dice": availability_dice,
                },
            },
        )


def remove_core_rules(apps, schema_editor):
    game_rule_model = apps.get_model("campaign", "GameRuleDef")
    game_rule_model.objects.using(schema_editor.connection.alias).filter(
        code="core"
    ).delete()
    shop_model = apps.get_model("campaign", "ShopDef")
    shop_model.objects.using(schema_editor.connection.alias).filter(
        name__in=["Village Market", "Town Market", "City Market"]
    ).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("campaign", "0009_rename_steplog_indexes"),
    ]

    operations = [
        migrations.CreateModel(
            name="GameRuleDef",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=40, unique=True)),
                ("name", models.CharField(max_length=120)),
                ("definition", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.RunPython(seed_core_rules, remove_core_rules),
    ]
