# Generated by Django 6.1.1 on 2026-10-01 00:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("campaign", "0010_gameruledef"),
    ]

    operations = [
        migrations.AddField(
            model_name="party",
            name="current_location_name",
            field=models.CharField(default="Village", max_length=120),
        ),
        migrations.AddField(
            model_name="party",
            name="current_settlement_size",
            field=models.CharField(
                choices=[("village", "Village"), ("town", "Town"), ("city", "City")],
                default="village",
                max_length=20,
            ),
        ),
    ]
